### ISSUE TITLE
Plugin fails when SVG files are required

### ISSUE THREAD

**Issue by mririgoyen** [Ephem/rollup-plugin-preserve-directives#14]
When using this plugin and importing an SVG file for inclusion, rollup fails to build. Removal of the SVG file allows things to build normally again. Please advise.

```tsx
import MyLogoSVG from '../../assets/images/logo.svg';
```

The error:
```
[!] (plugin preserve-directives) SyntaxError: Unexpected token (1:0)
src/assets/images/logo.svg (1:0)
    at Parser.pp$4.raise (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:22778:13)
    at Parser.pp$9.unexpected (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:19989:8)
    at Parser.pp$5.parseExprAtomDefault (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:22149:8)
    at Parser.pp$5.parseExprAtom (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:22144:17)
    at Parser.pp$5.parseExprSubscripts (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:21928:19)
    at Parser.pp$5.parseMaybeUnary (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:21894:17)
    at Parser.pp$5.parseExprOps (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:21821:19)
    at Parser.pp$5.parseMaybeConditional (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:21804:19)
    at Parser.pp$5.parseMaybeAssign (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:21771:19)
    at Parser.pp$5.parseExpression (/Users/mirigoye/Code/ids/node_modules/rollup/dist/shared/rollup.js:21734:19)
```

**Comment by Ephem** [comment]
Hey! Sorry for being a bit slow to reply, vacation mode. Sometimes errors seem to come from this plugin even though it's not the cause, just because it's the first plugin that parses the code (and it sometimes also swallows some error details). It might be that you need to reorder you plugins a bit to any plugin that handles svg imports comes before this plugin?

Created an issue to track here: https://github.com/Ephem/rollup-plugin-preserve-directives/issues/15

**Comment by mririgoyen** [comment]
I honestly believe it is this plugin after toying with it for several hours last night. It doesn't matter where in the plugin list it goes, the error is always there and always the same. I was able to get a little more error information to output at one point that I captured here:

```
  pos: 0,
  loc: Position { line: 1, column: 0 },
  raisedAt: 1,
  code: 'PLUGIN_ERROR',
  plugin: 'preserve-directives',
  hook: 'transform',
  id: '/Users/mirigoye/Code/ids/src/assets/images/logo.svg',
```

**Comment by mririgoyen** [comment]
I got to spend some more time with this last night. It turns out, I stupidly was not actually calling the SVGR plugin in the array. So, my apologies for blaming this plugin; you were correct.

I think a definite improvement would be to somehow indicate where the errors are coming from so you don't get so many false reports. Thanks for your work on this!

**Comment by Ephem** [comment]
Sorry for not following up on this, just got back from vacation. I'm glad you found the solution, and thank you for reporting back! 😃
